package hap_org.core.map.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.system.dto.BaseDTO;


public class LVEmployee {

     private String positionCode;

     private String employeename; //员工姓名

     private String hrcode; //员工编码

     private String brandcode; //品牌编码

     private String counterid; //柜台ID

     private String gender; //性别

     private String bcstatusnew; //状态

     private String email; //电子邮件

     private String mobilenumber; //移动电话

     private String hrposition; //员工岗位

     private String bcoroffice; //移动电话

     private String higherLevel1; //直接上级主管

     private String higherLevel2; //二级上级主管

    public LVEmployee() {
    }

    public void setPositionCode(String positionCode){
         this.positionCode = positionCode;
     }

     public String getPositionCode(){
         return positionCode;
     }

     public void setEmployeename(String employeename){
         this.employeename = employeename;
     }

     public String getEmployeename(){
         return employeename;
     }

     public void setHrcode(String hrcode){
         this.hrcode = hrcode;
     }

     public String getHrcode(){
         return hrcode;
     }

     public void setBrandcode(String brandcode){
         this.brandcode = brandcode;
     }

     public String getBrandcode(){
         return brandcode;
     }

     public void setCounterid(String counterid){
         this.counterid = counterid;
     }

     public String getCounterid(){
         return counterid;
     }

     public void setGender(String gender){
         this.gender = gender;
     }

     public String getGender(){
         return gender;
     }

     public void setBcstatusnew(String bcstatusnew){
         this.bcstatusnew = bcstatusnew;
     }

     public String getBcstatusnew(){
         return bcstatusnew;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setMobilenumber(String mobilenumber){
         this.mobilenumber = mobilenumber;
     }

     public String getMobilenumber(){
         return mobilenumber;
     }

     public void setHrposition(String hrposition){
         this.hrposition = hrposition;
     }

     public String getHrposition(){
         return hrposition;
     }

     public void setBcoroffice(String bcoroffice){
         this.bcoroffice = bcoroffice;
     }

     public String getBcoroffice(){
         return bcoroffice;
     }

     public void setHigherLevel1(String higherLevel1){
         this.higherLevel1 = higherLevel1;
     }

     public String getHigherLevel1(){
         return higherLevel1;
     }

     public void setHigherLevel2(String higherLevel2){
         this.higherLevel2 = higherLevel2;
     }

     public String getHigherLevel2(){
         return higherLevel2;
     }

     }
