package hap_org.core.map.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "hr_org_position_b")
public class OrgPositionB extends BaseDTO {


     public static final String FIELD_POSITION_ID = "positionId";
     public static final String FIELD_UNIT_ID = "unitId";
     public static final String FIELD_POSITION_CODE = "positionCode";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_PARENT_POSITION_ID = "parentPositionId";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";



     @Id
     @GeneratedValue
     private Long positionId;

     @NotNull
     private Long unitId; //组织ID

     @Length(max = 50)
     private String positionCode; //岗位编码

     @NotEmpty
     @Length(max = 100)
     @MultiLanguageField
     private String name;

     @Length(max = 255)
     @MultiLanguageField
     private String description; //岗位描述

     private Long parentPositionId; //父岗位ID

     @NotEmpty
     @Length(max = 1)
     private String enabledFlag; //启用状态




     public void setPositionId(Long positionId){
         this.positionId = positionId;
     }

     public Long getPositionId(){
         return positionId;
     }

     public void setUnitId(Long unitId){
         this.unitId = unitId;
     }

     public Long getUnitId(){
         return unitId;
     }

     public void setPositionCode(String positionCode){
         this.positionCode = positionCode;
     }

     public String getPositionCode(){
         return positionCode;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setParentPositionId(Long parentPositionId){
         this.parentPositionId = parentPositionId;
     }

     public Long getParentPositionId(){
         return parentPositionId;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
