package hap_org.core.map.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "hr_org_unit_b")
public class OrgUnitB extends BaseDTO {

     public static final String FIELD_UNIT_ID = "unitId";
     public static final String FIELD_PARENT_ID = "parentId";
     public static final String FIELD_UNIT_CODE = "unitCode";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_MANAGER_POSITION = "managerPosition";
     public static final String FIELD_COMPANY_ID = "companyId";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_UNIT_CATEGORY = "unitCategory";
     public static final String FIELD_UNIT_TYPE = "unitType";

    //判断是哪个表
    @Transient
    private Long tableId;

     @Id  //主键
     @GeneratedValue
     private Long unitId;

     private Long parentId; //父组织

     @Length(max = 50)
     private String unitCode; //组织编码

     @NotEmpty
     @Length(max = 100)
     @MultiLanguageField
     private String name;

     @Length(max = 255)
     @MultiLanguageField
     private String description; //组织描述

     private Long managerPosition; //组织管理岗位

     private Long companyId; //公司ID

     @NotEmpty
     @Length(max = 1)
     private String enabledFlag; //启用状态

     @Length(max = 50)
     private String unitCategory; //组织类别

     @Length(max = 50)
     private String unitType; //组织分类

    public void setableId(Long positionId){
        this.tableId = tableId;
    }

    public Long gettableId(){
        return tableId;
    }

     public void setUnitId(Long unitId){
         this.unitId = unitId;
     }

     public Long getUnitId(){
         return unitId;
     }

     public void setParentId(Long parentId){
         this.parentId = parentId;
     }

     public Long getParentId(){
         return parentId;
     }

     public void setUnitCode(String unitCode){
         this.unitCode = unitCode;
     }

     public String getUnitCode(){
         return unitCode;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setManagerPosition(Long managerPosition){
         this.managerPosition = managerPosition;
     }

     public Long getManagerPosition(){
         return managerPosition;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setUnitCategory(String unitCategory){
         this.unitCategory = unitCategory;
     }

     public String getUnitCategory(){
         return unitCategory;
     }

     public void setUnitType(String unitType){
         this.unitType = unitType;
     }

     public String getUnitType(){
         return unitType;
     }


}
